name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Use the latest stable Deno version

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Deno install deps
        run: deno install

      - name: Check format
        run: deno fmt --check

      #      # Optional: Add linting for style and syntax checks
      #      - name: Lint code
      #        run: deno lint
      #
      - name: Build wasm
        run: deno task build

      - name: Run tests
        run: deno test -A --no-check packages/extension-markdown/test/
#        run: deno test -A

      - name: Install Playwright browsers
        run: deno run -A npm:playwright@1.49.1 install --with-deps chromium

      - name: Run Playwright tests
        run: deno task test
        working-directory: examples/browser-react
