name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Use the latest stable Deno version

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Deno install deps
        run: deno install

      - name: Check format
        run: deno fmt --check

      #      - name: Lint code
      #        run: deno lint

      - run: deno task -f @kerebron/odt-wasm build # Future Deno versions may add cross-package task dependencies
      - run: deno task -f @kerebron build
      #      - run: deno task -f browser- build

      - name: Run tests md
        run: deno test -A --no-check packages/extension-markdown/test/
      - name: Run tests odt
        run: deno test -A --no-check packages/extension-odt/test/
      - name: Run tests odt
        run: deno test -A --no-check packages/extension-yjs/test/
